services:
  zookeeper-0:
    image: iartifactory.infinera.com/nm/zookeeper:3.5.6
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: |
        server.1=zookeeper-0:2888:3888;2181
        server.2=zookeeper-1:2888:3888;2181
        server.3=zookeeper-2:2888:3888;2181
      ZOO_ENABLE_4LW_CMD: "true"
    ports:
      - 12181:2181
  zookeeper-1:
    image: iartifactory.infinera.com/nm/zookeeper:3.5.6
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: |
        server.1=zookeeper-0:2888:3888;2181
        server.2=zookeeper-1:2888:3888;2181
        server.3=zookeeper-2:2888:3888;2181
      ZOO_ENABLE_4LW_CMD: "true"
    ports:
      - 22181:2181
  zookeeper-2:
    image: iartifactory.infinera.com/nm/zookeeper:3.5.6
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: |
        server.1=zookeeper-0:2888:3888;2181
        server.2=zookeeper-1:2888:3888;2181
        server.3=zookeeper-2:2888:3888;2181
      ZOO_ENABLE_4LW_CMD: "true"
    ports:
      - 32181:2181
  kafka-0:
    image: iartifactory.infinera.com/nm/kafka:2.4.0
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: "192.168.56.101:12181,192.168.56.101:22181,192.168.56.101:32181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.56.101:19092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:19092"
    network_mode: host
    ports:
      - 19092:19092
  kafka-1:
    image: iartifactory.infinera.com/nm/kafka:2.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "192.168.56.101:12181,192.168.56.101:22181,192.168.56.101:32181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.56.101:29092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092"
    network_mode: host
    ports:
      - 29092:29092
  kafka-2:
    image: iartifactory.infinera.com/nm/kafka:2.4.0
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "192.168.56.101:12181,192.168.56.101:22181,192.168.56.101:32181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.56.101:39092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:39092"
    network_mode: host
    ports:
      - 39092:39092